# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: registry.devops-mav.local/netflix-eureka
  tag: latest
  pullPolicy: Always

service:
  name:
  type: ClusterIP
  port: 8761
  internalPort: 8761

config:
  existingConfigMapName:

spring:
  cloud:
    config:
      enabled: false
      uri: http://central-config:8789

global:
  useConfigServerBootstrap: false
